INSERT INTO ProductEntity (id, title, description, cost) VALUES (1, 'Product Title 1', 'Product Description 1', 100.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (2, 'Product Title 2', 'Product Description 2', 200.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (3, 'Product Title 3', 'Product Description 3', 300.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (4, 'Product Title 4', 'Product Description 4', 400.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (5, 'Product Title 5', 'Product Description 5', 500.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (6, 'Product Title 6', 'Product Description 6', 600.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (7, 'Product Title 7', 'Product Description 7', 700.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (8, 'Product Title 8', 'Product Description 8', 800.00);
INSERT INTO ProductEntity (id, title, description, cost) VALUES (9, 'Product Title 9', 'Product Description 9', 900.00);
